### ISSUE TITLE
Marker Selection

### ISSUE THREAD

**Issue by LolloDev5123** [Delta-Applications/KaiMap#3]
- [x] Add a way to select markers, open a menu for each of them, delete, save as geojson, share position, and a plus code will show in the menu, there will also be a special menu for the my location marker. This will be integrated with the * key.

**Comment by strukturart** [comment]
that is my solution to select a marker : https://github.com/strukturart/o.map/blob/06f9fd86a8e5aa21c5d5e7fee830fee0c010990a/application/assets/js/module.js#L25

**Comment by LolloDev5123** [comment]
Thanks! I'll look into it, right now Im working on integrating Native KaiUI and making it fit the style. :)
