### ISSUE TITLE
Offline waypoint creation

### ISSUE THREAD

**Issue by Mikeruss** [Delta-Applications/KaiMap#9]
When making waypoint in offline mode (no any connection) they are not displayed on the screen until connection will be established for the firs time. Need to be fixed.

**Comment by LolloDev5123** [comment]
Can you show me a video? Waypoints created using 9 work perfectly fine without connection.

**Comment by Mikeruss** [comment]
Oh, yes, it works fine with 9! My mistake :) I'm initially tried to use key 5 to make waypoints. Then you make it with 5 with no connection, they are not displayed until you open the file (upd: not when connection established). Have no idea how to make video from the screen.
And another thing: when saving waypoints with 5 bottom menus does not disappear after saving (until you enter in the menu or restart). 
How to delete waypoints files? In my Nokia 800 when I long-press enter Google assistant runs by default.

It also could be good to load some file with points by default (specify in the menu), and maybe adding points in it.  

(my version is 1.2.4)

**Comment by LolloDev5123** [comment]
5 Saves position to a GeoJSON File, while 8 saves all markers that you made using 9

**Comment by LolloDev5123** [comment]
You can use the 2 key to search for cities with Internet, and you can delete waypoint files using your computer

**Comment by Mikeruss** [comment]
Ok, thank you. It works with the computer. 
I meant that it could be good to autoload some preliminary saved file with w.points when app starts and add new w.points in it. Same as in Garmin GPS: you can see all waypoints immediately when it turns on

**Comment by LolloDev5123** [comment]
Yes! I would do something like that, but first I would need to categorize waypoints, like the different icons garmin uses
